### ISSUE TITLE
Inhaltsüberblick: Video stopt bei 2:39

### ISSUE THREAD

**Issue by leakuhlmann** [oer-des/OER-Energieinformatik#1]
video stopt bei Minute 2:39 -> wenn ich dann auf Play klicke, fängt es wieder von vorne an, wenn ich irgendeine Minute > 2:39 anklicke, fängt es ebenfalls von vorne an
https://liascript.github.io/course/?https://raw.githubusercontent.com/oer-des/OER-Energieinformatik/main/Inhaltsueberblick.md#3

**Comment by oer-des** [comment]
Ich kann das nicht reproduzieren bei mir, welchen Browser nutzt du?

**Comment by JuliaHeiken** [comment]
Ich kann das nicht reproduzieren bei mir, welchen Browser nutzt du?

**Comment by leakuhlmann** [comment]
hab es gerade nochmal probiert und jetzt läuft es. Hatte es beim Auftreten mit Edge und Firefox probiert aber scheint sich jetzt erledigt zu haben :)
