### ISSUE TITLE
this issue to be deleted

### ISSUE THREAD

**Issue by di8007** [oer-des/OER-Energieinformatik#19]

**Comment by di8007** [comment]
Coordination tasks.
more example quizzes:
Why does voltage control become essential in power networks, and how is it achieved?

**Comment by di8007** [comment]
Components.
for this learning material it is clear and understandable.

**Comment by di8007** [comment]
Basics of electrical energy.
In this learning material, it is fine as a basics knowledge. However, more description
in the section (Wichtige Großen und Begriffe) is recommended.
For example:
1- Description text before the quizzes would be perfect.
2- More details for the section (Leistung und elektrische Energie)

**Comment by di8007** [comment]
Energy market
would be beneficial to include a small description about
Merit order concepts and related questions.
For example:
1- What major change in the energy market structure occurred in the 1980s, leading
to increased competition?
2- What does the Merit order refer to in energy markets?
3- What is the main difference between the Day-Ahead Market and the intraday
market?
Figures 3,5,6 need more description for better understanding

**Comment by di8007** [comment]
Operation planning.
well written and clear. one question is recommended:
- What is the primary focus of unit commitment in power plant operation?

**Comment by di8007** [comment]
Overview of the lecture’s content.
In this learning material, a well summarizing of the lectures contents, gives perfect
overview to the materials. The questions and video are fulfilled and consolidate the
knowledge understanding.

**Comment by di8007** [comment]
Demand side management.
Clear to understand, but it would be beneficial to add a brief definition for DSM and
its techniques, along with a concise text about the limitations of such operations,
explaining why they have not been widely adopted

**Comment by JuliaHeiken** [comment]
Hi Diaa, please create one issue for each suggestion for improvement. We don't need the "good" aspects here, only issues we should work on. And please add the corresponding Liascript learning object + page in the Liascript course. Thank you!
