### ISSUE TITLE
empfohlene Reihenfolge der Lerneinheiten?

### ISSUE THREAD

**Issue by leakuhlmann** [oer-des/OER-Energieinformatik#2]
gitb es eine empfohlene Reihenfolge, in der die Lerneinheiten durchgearbeitet werden sollten? teilweise referenzieren sie aufeinander, aber ich habe diese "optimale Reihenfolge" nicht finden können - vielleicht sinnvoll, die in Studyguide oder Inhaltsübersicht zu ergänzen?

**Comment by JuliaHeiken** [comment]
Es gibt keine vorgegebene Reihenfolge, da die Themen relativ unabhängig voneinander und in beliebiger Reihenfolge bearbeitbar sein sollen.
