### ISSUE TITLE
Abkürzungen auf der Mindmap einführen?

### ISSUE THREAD

**Issue by leakuhlmann** [oer-des/OER-Energieinformatik#3]
Einige Abkürzungen in der Mindmap sind für Leute, die neu in dem Themengebiet sind, vlt nicht verständlich - ausschreiben und Abkürzungen einführen oder kurze Erklärungen verlinken?

**Comment by JuliaHeiken** [comment]
Genaue Angaben bitte, welche Abkürzungen gemeint sind.

**Comment by leakuhlmann** [comment]
z. B.
HITL
RTDS
SGAM
ERP
SDL

**Comment by JuliaHeiken** [comment]
@JuliaHeiken Abkürzungsverzeichnis verlinken
