### ISSUE TITLE
Antworten auf "Zum Nachdenken und vertiefen"

### ISSUE THREAD

**Issue by leakuhlmann** [oer-des/OER-Energieinformatik#4]
https://liascript.github.io/course/?https://raw.githubusercontent.com/oer-des/OER-Energieinformatik/main/DemandSideManagement.md#8
hier sind Fragen zum Nachdenken und vertiefen formuliert - sind auch die Antworten irgendwo zu finden?

**Comment by JuliaHeiken** [comment]
Für die "zum Nachdenken" Kästen gibt es keine Musterlösungen - die Fragen sollte jede/r leicht beantworten können, der/die das Material durcharbeitet.
