### ISSUE TITLE
Verständlichkeit Begriffe

### ISSUE THREAD

**Issue by leakuhlmann** [oer-des/OER-Energieinformatik#5]
Einige Begriffe, die glaube ich nicht bei der ersten Verwendung erklärt werden, könnten für Neulinge im Thema Fragen aufwerfen, zB:
- Umrichter-gekoppelte Anlage 
- stochastische Erzeuger

**Comment by JuliaHeiken** [comment]
@leakuhlmann welches Lernobjekt und sind das alle Begriffe, die unklar sind?

**Comment by leakuhlmann** [comment]
@JuliaHeiken 
Umrichter-gekoppelte Anlage -> in "Komponenten"
stochastischer Erzeuger -> in "DSM" und "Einsatzplanung"

aus meiner Sicht ja
