### ISSUE TITLE
Link funktioniert nicht

### ISSUE THREAD

**Issue by leakuhlmann** [oer-des/OER-Energieinformatik#7]
auf folgender Seite
https://liascript.github.io/course/?https://raw.githubusercontent.com/oer-des/OER-Energieinformatik/main/Koordinationsaufgaben.md#3
ist ein Link zur Netzfrequenzmessung eingebaut, der nicht funktioniert.

**Comment by JuliaHeiken** [comment]
@JuliaHeiken Link anpassen
