### ISSUE TITLE
Grafik

### ISSUE THREAD

**Issue by leakuhlmann** [oer-des/OER-Energieinformatik#8]
wofür stehen die Ps in der Abbildung? Die Leiste links ist für mich nicht ganz verständlich :)
https://liascript.github.io/course/?https://raw.githubusercontent.com/oer-des/OER-Energieinformatik/main/Smart_Grid.md#8

**Comment by JuliaHeiken** [comment]
@JuliaHeiken Erklärung in Bildunterschrift hinzufügen.
