### ISSUE TITLE
Link funktioniert nicht

### ISSUE THREAD

**Issue by leakuhlmann** [oer-des/OER-Energieinformatik#9]
ganz unten auf folgender Seite: https://liascript.github.io/course/?https://raw.githubusercontent.com/oer-des/OER-Energieinformatik/main/Inhaltsueberblick.md#7

ist die Gesellschaft für Informatik, Fachgruppe Energieinformatik verlinkt -> der Link führt zu einer Fehlermeldung

**Comment by JuliaHeiken** [comment]
@JuliaHeiken Link anpassen auf https://fg-wi-eins.gi.de/
